---
title: "all_dogs_Ctrl"
author: "Lucrezia Lonardo"
date: "15/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

library(lme4)
library(ggthemes)
library(psych)
library(summarytools)
library(cowplot)
library(car)
library(tidyverse)
library(readr)
library(ggsignif)
library(multcomp)
source("functions/diagnostic_fcns.r")
source("functions/glmm_stability.r")
source("functions/boot_glmm.r")
```
import data
```{r include=FALSE}
ctrl_data<- read.csv("data/Dataset_S2.csv")%>%
  mutate(condition=recode(condition, "False_Belief"="False Belief", "True_Belief"="True Belief","True_Belief_Control"="True Belief Control"))
```
## GLMM with breed as random intercept investigating the effect of condition on choice. Table S5

```{r}
xx.fe.re=fe.re.tab(fe.model="correct ~ condition + age + sex + first_baited_box",
                   re="(1|breed)", data=ctrl_data)
xx.fe.re$summary
```

#### fitting the model with "True Belief Control" as reference category for condition
``` {r error=TRUE}
# centering variables for modeling

model.data2 <- ctrl_data %>% 
  mutate(condition=fct_relevel(condition, ref="True_Belief_Control"),
         z.age = as.numeric(scale(age, scale = T, center = T)),
         sex.c = as.numeric(scale(as.numeric(as.factor(sex)), scale=F, center=T)),
         condition.c = as.numeric(scale(as.numeric(as.factor(condition)), scale=F, center=T)),
         first_baited_box.c = as.numeric(scale(as.numeric(as.factor(first_baited_box)), scale=F, center=T)))

as.data.frame(model.data2)

## code to run the model
full.choice.breed2 <- glmer(correct ~ condition + z.age + sex + first_baited_box+
             (1+ sex.c + condition.c + first_baited_box.c + z.age|| breed), 
             data = model.data2, family = binomial, 
             control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))
)
```
####Model output with relevelled condition variable
  + Coefficients
```{r}
round(summary(full.choice.breed2)$coefficients, 3)
```
#Chisq. (LRT) and p
```{r}
drop1.full=drop1(full.choice.breed2, test="Chisq")
round(drop1.full,3)
```
```{r}
summary(full.choice.breed2)$varcor
summary(full.choice.breed2)
```
```{r}
#confidence intervals
boot.res=boot.glmm.pred(model.res=full.choice.breed2, excl.warnings=T,
	nboots=1000, para=T)
res<-round(boot.res$ci.estimates, 3)
res
```
#Plotting the choices: Figure 2
```{r}
#confidence intervals: fitting a new model for the CI

ci.data <- ctrl_data %>% 
  mutate(z.age = as.numeric(scale(age, scale = T, center = T)),
         sex.c = as.numeric(scale(as.numeric(sex), scale=F, center=T)),
         condition.c = as.numeric(scale(as.numeric(condition), scale=F, center=T)),
         first_baited_box.c = as.numeric(scale(as.numeric(first_baited_box), scale=F, center=T)))

as.data.frame(ci.data)


full.choice.breed.ci <- glmer(correct ~ condition + z.age + sex.c + first_baited_box.c +
             (1+ sex.c + condition.c + first_baited_box.c || breed),
             data = ci.data, family = binomial,
             control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))
)


boot.res=boot.glmm.pred(model.res=full.choice.breed.ci, excl.warnings=T,
	nboots=1000, use="condition", para=T)
resf<-boot.res$ci.predicted
resf

#for plotting
fblower<-resf[1,6]
fbupper<-resf[1,7]
tblower<-resf[2,6]
tbupper<-resf[2,7]
tbctrlower<-resf[3,6]
tbctrupper<-resf[3,7]

df<-data.frame(lower.ci=c(fblower,tblower,tbctrlower),
  upper.ci=c(fbupper, tbupper, tbctrupper))
fv=c(resf$fitted[1],resf$fitted[2], resf$fitted[3])
fv
```
#plot with CI and fitted values. Figure 2

```{r}
#plotting the choices with error bars depicting CI
plot.data <- ctrl_data %>%
  group_by(condition)%>%
  summarise(mean.correct=mean(correct), sd.correct=sd(correct), sum.correct=sum(correct), median.correct=median(correct), n.correct=length(correct), se.correct=sd(correct)/sqrt(length(correct)))
plot.data


p.choice<-ggplot(
  data=plot.data, aes(x=condition, y=mean.correct)) +
  geom_bar(stat="identity", alpha=0.5)+
  geom_errorbar(aes(ymin=df$lower.ci, ymax=df$upper.ci), width=.2)+
  geom_point(aes(x=condition, y=fv)) +
  ylim(0,0.8)+
  geom_signif(comparisons=list(c("False Belief", "True Belief")), annotations="*",
              y_position = 0.76, tip_length = 0.04, vjust=0.4) +
  geom_signif(comparisons=list(c("False Belief","True Belief Control")), annotations="*",
              y_position = 0.70, tip_length = 0.04, vjust=0.4) +
  theme_classic()+
  labs(x="Group",y="Proportion of bucket A choices")+
  ggtitle("Choice (N=180)")
 p.choice
 
 #saving the plot with ggsave
 ggsave(
  "Fig_2_bucket_A_choices_180_dogs_fv_CI.pdf",
  plot = last_plot(),
  device = NULL,
  path = "~/GitHub/data_code_Lonardo_et_al/graphs",
  scale = 0.8,
  width = 7,
  height = 6,
  units = c("in", "cm", "mm"),
  dpi = 320,
  limitsize = TRUE
)
 

#(A choice= 0.48 fb; 0.29 tb; 0.28 tbc)

```

